# Generated by Django 4.2.5 on 2023-10-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=3, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phoneNumber', models.CharField(max_length=11)),
            ],
        ),
    ]
