# Generated by Django 4.2.5 on 2023-10-17 16:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apps', '0003_author_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('avatar', models.ImageField(default='static/images/image_blogs', max_length=255, null=True, upload_to='static/images/image_blogs')),
                ('firstImage', models.ImageField(default='static/images/image_blogs', max_length=255, null=True, upload_to='static/images/image_blogs')),
                ('secondImage', models.ImageField(default='static/images/image_blogs', max_length=255, null=True, upload_to='static/images/image_blogs')),
                ('thirdImage', models.ImageField(default='static/images/image_blogs', max_length=255, null=True, upload_to='static/images/image_blogs')),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('city_blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_blog', to='apps.city')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_comment', models.TextField()),
                ('date_comment', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='apps.blogs')),
                ('user_comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
