# Generated by Django 4.2.5 on 2023-10-17 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_blogs_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date_comment',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
