# Generated by Django 4.2.5 on 2023-10-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_alter_comments_date_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='avatar',
            field=models.ImageField(default='static/images/profiles', max_length=255, null=True, upload_to='static/images/profiles'),
        ),
    ]
