# Generated by Django 4.2.5 on 2023-10-24 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_blogs_description1_blogs_description2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
