# Generated by Django 4.2.5 on 2023-10-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_remove_customer_user_alter_booktour_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='description2',
            field=models.TextField(null=True),
        ),
    ]
