# Generated by Django 4.2.5 on 2023-10-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_tour_description_tour_description1_tour_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description2',
        ),
    ]
